"""Docker Compose and .env file generator.

ComposeGenerator has one responsibility: assembling the final compose
document from service definitions. It does not know how any individual
service is configured — that is owned by the service classes in
``tools/lib/services/``.
"""

import copy
import secrets
from pathlib import Path
from typing import Any

import yaml

from lib.services import SERVICE_REGISTRY


def generate_env(config: dict[str, Any], output_path: Path) -> None:
    """Generate a .env file from configuration.

    Args:
        config: The project configuration dictionary.
        output_path: Path to write the .env file.
    """
    # Only secrets belong in .env.
    # Non-secret values are inlined directly into the generated compose file.
    env_vars = {
        "HF_TOKEN": str(config.get("huggingface", {}).get("token", "")),
    }

    with open(output_path, "w") as f:
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")


def generate_compose(config: dict[str, Any], output_path: Path) -> None:
    """Generate a Docker Compose file from configuration.

    Asks the service registry for every enabled service, collects their
    definitions, and writes the final compose YAML.

    Args:
        config: The project configuration dictionary.
        output_path: Path to write the generated compose file.
    """

    # Never mutate the original configuration
    config = copy.deepcopy(config)

    # ------------------------------------------------------------------
    # Gateway Authentication
    # ------------------------------------------------------------------
    gateway_cfg = config.get("gateway")
    if gateway_cfg is None:
        raise ValueError("Missing 'gateway' section in config.yaml")

    auth_cfg = gateway_cfg.get("authentication")
    if auth_cfg is None:
        raise ValueError(
            "Missing 'gateway.authentication' section in config.yaml"
        )

    if auth_cfg.get("enabled", False):
        api_key = auth_cfg.get("api_key")

        if api_key == "auto":
            auth_cfg["api_key"] = (
                f"sk_selfai_{secrets.token_urlsafe(32)}"
            )
        elif not api_key:
            raise ValueError(
                "gateway.authentication.api_key must be 'auto' "
                "or a non-empty string"
            )

    # ------------------------------------------------------------------
    # Build enabled services
    # ------------------------------------------------------------------
    services: dict[str, Any] = {}

    for svc in SERVICE_REGISTRY.enabled_services(config):
        if hasattr(svc, "iter_builds"):
            for service_name, definition in svc.iter_builds(config):
                services[service_name] = definition
        else:
            services[svc.service_name(config)] = svc.build(config)

    compose: dict[str, Any] = {
        "services": services,
        "networks": {
            "ai-network": {
                "driver": "bridge",
            },
        },
    }

    with open(output_path, "w") as f:
        f.write("# Auto-generated by self-hosted-ai. Do not edit manually.\n")
        f.write("# Regenerate with: python3 tools/generate.py\n\n")
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)