"""Docker Compose and .env file generator.

ComposeGenerator has one responsibility: assembling the final compose
document from service definitions.  It does not know how any individual
service is configured — that is owned by the service classes in
``tools/lib/services/``.
"""

from pathlib import Path
from typing import Any

import yaml

from lib.services import SERVICE_REGISTRY


def generate_env(config: dict[str, Any], output_path: Path) -> None:
    """Generate a .env file from configuration.

    Args:
        config: The project configuration dictionary.
        output_path: Path to write the .env file.
    """
    env_vars = {
        "TZ": "UTC",
        "HF_TOKEN": str(config["model"].get("hf_token", "")),
        "MODEL_CACHE_DIR": str(config["model"]["download_dir"]),
    }
    with open(output_path, "w") as f:
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")


def generate_compose(config: dict[str, Any], output_path: Path) -> None:
    """Generate a Docker Compose file from configuration.

    Asks the service registry for every enabled service, collects their
    definitions, and writes the final compose YAML.  ComposeGenerator has
    no knowledge of how individual services are built.

    Args:
        config: The project configuration dictionary.
        output_path: Path to write the generated compose file.
    """
    services: dict[str, Any] = {}
    for svc in SERVICE_REGISTRY.enabled_services(config):
        services[svc.service_name(config)] = svc.build(config)

    compose: dict[str, Any] = {
        "services": services,
        "networks": {
            "ai-network": {
                "driver": "bridge",
            },
        },
    }

    with open(output_path, "w") as f:
        f.write("# Auto-generated by self-hosted-ai. Do not edit manually.\n")
        f.write("# Regenerate with: python3 tools/generate.py\n\n")
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)

