"""Docker Compose and .env file generator."""

from pathlib import Path
from typing import Any

import yaml

from lib.runtime import get_runtime_adapter


def generate_env(config: dict[str, Any], output_path: Path) -> None:
    """Generate a .env file from configuration.

    Args:
        config: The project configuration dictionary.
        output_path: Path to write the .env file.
    """
    env_vars = {
        "TZ": "UTC",
        "HF_TOKEN": str(config["model"].get("hf_token", "")),
        "MODEL_CACHE_DIR": str(config["model"]["download_dir"]),
    }
    with open(output_path, "w") as f:
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")


def generate_compose(config: dict[str, Any], output_path: Path) -> None:
    """Generate a Docker Compose file from configuration.

    The runtime command section is produced by the appropriate runtime adapter.
    All other service definitions are built from the project configuration.

    Args:
        config: The project configuration dictionary.
        output_path: Path to write the generated compose file.
    """
    runtime = config["runtime"]
    engine = runtime["engine"]
    port = runtime["port"]

    adapter = get_runtime_adapter(engine)
    command = adapter.build_command(config)

    healthcheck_script = (
        "import urllib.request; "
        f"urllib.request.urlopen('http://localhost:{port}{adapter.health_endpoint}')"
    )

    compose: dict[str, Any] = {
        "services": {
            "caddy": {
                "image": "caddy:2.10",
                "container_name": "caddy",
                "restart": "unless-stopped",
                "ports": ["80:80"],
                "depends_on": ["open-webui"],
                "volumes": [
                    "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro",
                    "./data/caddy:/data",
                    "./data/caddy:/config",
                ],
                "networks": ["ai-network"],
            },
            engine: {
                "image": adapter.image,
                "container_name": engine,
                "restart": "unless-stopped",
                "runtime": "nvidia",
                "ipc": "host",
                "command": command,
                "environment": {
                    "HUGGING_FACE_HUB_TOKEN": "${HF_TOKEN}",
                },
                "volumes": [
                    "${MODEL_CACHE_DIR}:/root/.cache/huggingface",
                ],
                "expose": [str(port)],
                "healthcheck": {
                    "test": ["CMD", "python3", "-c", healthcheck_script],
                    "interval": "10s",
                    "timeout": "5s",
                    "retries": 60,
                    "start_period": "120s",
                },
                "networks": ["ai-network"],
            },
            "open-webui": {
                "image": "ghcr.io/open-webui/open-webui:main",
                "container_name": "open-webui",
                "restart": "unless-stopped",
                "depends_on": {
                    engine: {"condition": "service_healthy"},
                },
                "expose": ["8080"],
                "environment": {
                    "TZ": "${TZ}",
                    "OPENAI_API_BASE_URL": f"http://{engine}:{port}/v1",
                    "OPENAI_API_KEY": "dummy",
                },
                "volumes": [
                    "./data/open-webui:/app/backend/data",
                ],
                "networks": ["ai-network"],
            },
        },
        "networks": {
            "ai-network": {
                "driver": "bridge",
            },
        },
    }

    with open(output_path, "w") as f:
        f.write("# Auto-generated by self-hosted-ai. Do not edit manually.\n")
        f.write("# Regenerate with: python3 tools/generate.py\n\n")
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)
