services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui

    restart: unless-stopped

    ports:
      - "3000:8080"

    environment:
      TZ: ${TZ}

    volumes:
      - ./data/open-webui:/app/backend/data

    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge